name: Rust

on:
  push:
    branches: [ Xv2 ]
  pull_request:
    branches: [ Xv2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
